require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: disable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - !ruby/regexp /old_and_unused\.rb$/