LOCAL_POSTGRES_USERNAME: 'postgres'
LOCAL_POSTGRES_PASSWORD: 'Wizard101'
SECRET_KEY_BASE: 'Base'
ENCRYPTION_SERVICE_SALT: '@\xECr\xFAQT+\xE5QJ\t\xF3\xA9<]\xAC\xD4\x8A\xDDM\xF0L\xF9Zz(\x0EuR\xF3g\x92'
JAVASCRIPT_DRIVER: :selenium_chrome_headless