name: Ruby Build

on:
  push:
    branches: [ $default-branch, dev ]
  pull_request:
    branches: [ $default-branch, dev ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: rspec -f d